# Generated by Django 2.0.1 on 2018-01-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_weekly_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
