# Generated by Django 2.0.1 on 2018-04-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeks.Week')),
                ('last_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_week', to='weeks.Week')),
            ],
        ),
    ]
