# Generated by Django 2.0.1 on 2018-01-15 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_day',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 58, 12, 759495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
